---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: update-pmml
rules:
  - apiGroups: ["apps"] # "" indicates the core API group
    resources: ["deployments"]
    verbs: ["*"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["configmaps"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: update-pmml
subjects:
  - kind: ServiceAccount
    name: {{ include "update-ppml.serviceAccountName" . }}
    namespace: default
roleRef:
  kind: Role
  name: update-pmml
  apiGroup: rbac.authorization.k8s.io